#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput


#/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000